package jsptest.dao;

import java.util.List;

public interface EmployeeDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    void insert(Employee record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    int updateByPrimaryKey(Employee record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    List selectByExample(EmployeeExample example, String orderByClause);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    List selectByExample(EmployeeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    Employee selectByPrimaryKey(String id);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    int deleteByPrimaryKey(String id);
}