package jsptest.dao;

public class EmployeeExample extends Employee {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public static final int EXAMPLE_IGNORE = 0;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public static final int EXAMPLE_NULL = 1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public static final int EXAMPLE_NOT_NULL = 2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public static final int EXAMPLE_EQUALS = 3;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public static final int EXAMPLE_NOT_EQUALS = 4;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public static final int EXAMPLE_GREATER_THAN = 5;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public static final int EXAMPLE_GREATER_THAN_OR_EQUAL = 6;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public static final int EXAMPLE_LESS_THAN = 7;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public static final int EXAMPLE_LESS_THAN_OR_EQUAL = 8;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public static final int EXAMPLE_LIKE = 9;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private boolean combineTypeOr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int id_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int name_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int deptcode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int deptname_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int unitcode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int unitname_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int pstncode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int pstnname_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int layercode_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int trnsflag_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int msnum_Indicator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private int nwId_Indicator;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setCombineTypeOr(boolean combineTypeOr) {
        this.combineTypeOr = combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public boolean isCombineTypeOr() {
        return combineTypeOr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getId_Indicator() {
        return id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setId_Indicator(int id_Indicator) {
        this.id_Indicator = id_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getName_Indicator() {
        return name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setName_Indicator(int name_Indicator) {
        this.name_Indicator = name_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getDeptcode_Indicator() {
        return deptcode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setDeptcode_Indicator(int deptcode_Indicator) {
        this.deptcode_Indicator = deptcode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getDeptname_Indicator() {
        return deptname_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setDeptname_Indicator(int deptname_Indicator) {
        this.deptname_Indicator = deptname_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getUnitcode_Indicator() {
        return unitcode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setUnitcode_Indicator(int unitcode_Indicator) {
        this.unitcode_Indicator = unitcode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getUnitname_Indicator() {
        return unitname_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setUnitname_Indicator(int unitname_Indicator) {
        this.unitname_Indicator = unitname_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getPstncode_Indicator() {
        return pstncode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setPstncode_Indicator(int pstncode_Indicator) {
        this.pstncode_Indicator = pstncode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getPstnname_Indicator() {
        return pstnname_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setPstnname_Indicator(int pstnname_Indicator) {
        this.pstnname_Indicator = pstnname_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getLayercode_Indicator() {
        return layercode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setLayercode_Indicator(int layercode_Indicator) {
        this.layercode_Indicator = layercode_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getTrnsflag_Indicator() {
        return trnsflag_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setTrnsflag_Indicator(int trnsflag_Indicator) {
        this.trnsflag_Indicator = trnsflag_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getMsnum_Indicator() {
        return msnum_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setMsnum_Indicator(int msnum_Indicator) {
        this.msnum_Indicator = msnum_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public int getNwId_Indicator() {
        return nwId_Indicator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table employee
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setNwId_Indicator(int nwId_Indicator) {
        this.nwId_Indicator = nwId_Indicator;
    }
}