package jsptest.dao;

public class Employee {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.id
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private String id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.name
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.deptcode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private String deptcode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.deptname
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private String deptname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.unitcode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private String unitcode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.unitname
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private String unitname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.pstncode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private String pstncode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.pstnname
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private String pstnname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.layercode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private Integer layercode;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.trnsflag
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private Integer trnsflag;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.msnum
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private Integer msnum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column employee.nw_id
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    private String nwId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.name
     *
     * @return the value of employee.name
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.name
     *
     * @param name the value for employee.name
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.deptcode
     *
     * @return the value of employee.deptcode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public String getDeptcode() {
        return deptcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.deptcode
     *
     * @param deptcode the value for employee.deptcode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setDeptcode(String deptcode) {
        this.deptcode = deptcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.deptname
     *
     * @return the value of employee.deptname
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.deptname
     *
     * @param deptname the value for employee.deptname
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.unitcode
     *
     * @return the value of employee.unitcode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public String getUnitcode() {
        return unitcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.unitcode
     *
     * @param unitcode the value for employee.unitcode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setUnitcode(String unitcode) {
        this.unitcode = unitcode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.unitname
     *
     * @return the value of employee.unitname
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public String getUnitname() {
        return unitname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.unitname
     *
     * @param unitname the value for employee.unitname
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setUnitname(String unitname) {
        this.unitname = unitname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.pstncode
     *
     * @return the value of employee.pstncode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public String getPstncode() {
        return pstncode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.pstncode
     *
     * @param pstncode the value for employee.pstncode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setPstncode(String pstncode) {
        this.pstncode = pstncode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.pstnname
     *
     * @return the value of employee.pstnname
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public String getPstnname() {
        return pstnname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.pstnname
     *
     * @param pstnname the value for employee.pstnname
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setPstnname(String pstnname) {
        this.pstnname = pstnname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.layercode
     *
     * @return the value of employee.layercode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public Integer getLayercode() {
        return layercode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.layercode
     *
     * @param layercode the value for employee.layercode
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setLayercode(Integer layercode) {
        this.layercode = layercode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.trnsflag
     *
     * @return the value of employee.trnsflag
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public Integer getTrnsflag() {
        return trnsflag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.trnsflag
     *
     * @param trnsflag the value for employee.trnsflag
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setTrnsflag(Integer trnsflag) {
        this.trnsflag = trnsflag;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.msnum
     *
     * @return the value of employee.msnum
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public Integer getMsnum() {
        return msnum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.msnum
     *
     * @param msnum the value for employee.msnum
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setMsnum(Integer msnum) {
        this.msnum = msnum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column employee.nw_id
     *
     * @return the value of employee.nw_id
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public String getNwId() {
        return nwId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column employee.nw_id
     *
     * @param nwId the value for employee.nw_id
     *
     * @abatorgenerated Mon Oct 13 14:44:28 JST 2014
     */
    public void setNwId(String nwId) {
        this.nwId = nwId;
    }
}